# Configure main menu and social menu
#[[main]]
#identifier = "主页"
#name = "主页"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/fQwQf"

[social.params]
icon = "brand-github"
